[package]
name = "search"
version = "23.6.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.3.4", features = ["derive"] }
openai = "1.0.0-alpha.11"
tokio = "1.28.2"
